apiVersion: v1
kind: Service
metadata:
  name: student-registration-service
spec: 
  selector:
    app: student-registration-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort